Form/logic
Lauren245/FurBook pull request #16
Opened 2024-11-16 03:06 UTC by Croaky16

Changed the parameters of inputs in the form.html and created logic for it in form.js

2024-11-16 19:57 UTC, Lauren245 requested changes
1. At a glance, I'm not exactly sure what the JavaScript in the form html is doing. The regex does seem to be preventing spaces from being added to the form fields and some words like golden retriever should be two words. 
2. You don't have to do the validation line by line in the form. Having prevent default at the very top of your form handing function (which I think it is somewhere else right now) should stop the form from processing long enough to check each line. I'd recommend doing data validation in the form.js file. There you can take the data you are retrieving in all those .value lines and use something similar to what you are doing to validate the results. 
3. You can alter your event listener to include the entire form and change it to listen for a submit event. This way you can consolidate things down to just one event listener.
4. You do not need the array of inputs, you can just use the values of the inputs you want to check and check them against requirements with an if statement. These values cannot be empty because the form has the required attribute.
5. It looks like the JS in the form.html is preventing people from entering incorrect types of data for each field in real time, this is cool but could be confusing to a user. All of this can be done in a more simplified manner using javascript to check for invalid values after the submit button has been clicked by using PreventDefault and then checking for invalid values.
6. I believe that JavaScript will not let someone enter information of a different data type into a field automatically. For example, it will only allow numbers if the input type is numbers.
7. Beyond making sure the fields are not empty (which is being accomplished by the required keyword) is making sure the pet's age is a positive number. Also, it might be a good idea to change phone number to a string since it is not part of a mathematical equation and you can use the built in string length property to make sure they entered enough characters. Plus local storage will convert everything into a string anyway. https://www.w3schools.com/jsref/jsref_length_string.asp 
8. It is a good idea to use let instead of var. They do the same thing, except let prevents something called variable hoisting. 
9. A cool thing about JavaScript is you don't have to create a variable for a boolean and then use comparison operators to check their value. !true is the same as false. If you want to assign it to a variable which it looks like you might then you can just check that value by doing the same thing but with the variable name (in this case if(!True)).
10. I would highly recommend changing  you variable name to something a bit more descriptive and less close to the name of a keyword. 
11. Once functions are added to do the local storage stuff, you will be calling that function and passing it the appointmentInfo object you make instead of adding it to local storage within the same function.
12. The form could use more bootstrap styling so it looks a little less default and the inputs don't span the entire screen.
13. 
Overall, what you did is quite cool and impressive, but there are ways to do the same things in a more efficient way with less code. Please let me know if you have any questions or if I can help with anything.

2024-11-16 21:48 UTC, Croaky16 commented
1. The JavaScript in form.html is preventing anything other than those specified inputs. I found that with just the type="number", the user can still input "e" and "-". I also found that type="text" still allows numbers, so I created parameters that allows only A-Z and a-z(uppercase and lowercase). Anything else and it will not be allowed to be inputted. Everything in the brackets such as ['Backspace', 'Delete', 'ArrowLeft', ,ArrowRight'](I will have to add 'Space' to the breed) are exceptions of what keys can be pressed during the time of input. This code inside the input checks for the right inputs in real time instead of after clicking submit. I have found problems with clicking the submit button. If the whole form is filled out(all required being fulfilled, which is all the submit button is checking for), the whole form clears. so by checking if everything is filled in before the form sees it by running the length of all the inputs through our own for loop, we can use prevent default to stop the form before it clears and use the inputs. Otherwise, it lets the form highlight which input is blank. This helps reduce the amount of code with all of the if statements. I can always adjust the parameters to what is needed. I hope this explanation from my point of view can help you understand a bit better in some areas.
2. I will take a look into the var and booleans. I will also look into styling the bootstrap a bit. Let me know if after my explanation you still would like certain things to be done.

2024-11-17 21:56 UTC, Lauren245 commented
> 1. The JavaScript in form.html is preventing anything other than those specified inputs. I found that with just the type="number", the user can still input "e" and "-". I also found that type="text" still allows numbers, so I created parameters that allows only A-Z and a-z(uppercase and lowercase). Anything else and it will not be allowed to be inputted. Everything in the brackets such as ['Backspace', 'Delete', 'ArrowLeft', ,ArrowRight'](I will have to add 'Space' to the breed) are exceptions of what keys can be pressed during the time of input. This code inside the input checks for the right inputs in real time instead of after clicking submit. I have found problems with clicking the submit button. If the whole form is filled out(all required being fulfilled, which is all the submit button is checking for), the whole form clears. so by checking if everything is filled in before the form sees it by running the length of all the inputs through our own for loop, we can use prevent default to stop the form before it clears and use the inputs. Otherwise, it lets the form highlight which input is blank. This helps reduce the amount of code with all of the if statements. I can always adjust the parameters to what is needed. I hope this explanation from my point of view can help you understand a bit better in some areas.
> 2. I will take a look into the var and booleans. I will also look into styling the bootstrap a bit. Let me know if after my explanation you still would like certain things to be done.

There are multiple ways to do the same thing in code, so as long as it does what is expected, which it looks like it does, then that is great. I would just recommend adding the space exception that you are working on and adding some code to the form validation that clears the input fields after the values are added to an object and passed to the local storage creation code, that should be good to go. If you have time, you could also add some additional bootstrap to create a success alert so the user knows the form was submitted successfully. https://getbootstrap.com/docs/5.3/components/alerts/

2024-11-17 21:57 UTC, Lauren245 approved these changes

2024-11-17 22:00 UTC, merged